In [2]:
import numpy as np
from sklearn import datasets

# Load Data

In [3]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [4]:
X = iris['data']
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
labels = np.unique(y)
labels

array([0, 1, 2])

# Split

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)
print(np.bincount(y))
print(np.bincount(y_train))
print(np.bincount(y_test))

[50 50 50]
[35 35 35]
[15 15 15]


# Normalize

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)            #  get mean and std from X_train, which used fo both - X_train and X-test
X_train_std = scaler.transform(X_train)
X_test_std = scaler.transform(X_test)

# Model

In [7]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=100.0, random_state=1, solver='lbfgs', multi_class='multinomial')
#
#  solver - 'newton-cg', 'lbfgs', 'liblinear ', 'sag', 'saga'   
#  multi_class - 'ovr', 'multinomial', 'auto
#
lr.fit(X_train_std, y_train)

LogisticRegression(C=100.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Validation

In [8]:
from sklearn.metrics import accuracy_score
y_pred = lr.predict(X_test_std)
print('accuracy - ', accuracy_score(y_test, y_pred))

accuracy -  1.0


# Predict

In [9]:
lr.predict_proba(X_test_std[:3, :])

array([[4.33988327e-09, 7.18922519e-04, 9.99281073e-01],
       [9.99691829e-01, 3.08170995e-04, 1.18453828e-20],
       [9.99945810e-01, 5.41899827e-05, 2.25308455e-21]])

In [10]:
lr.predict_proba(X_test_std[:3, :]).argmax(axis=1)

array([2, 0, 0])

In [11]:
prediction = lr.predict([[6, 3, 5, 2]])
print(target_names[prediction])


['virginica']


In [13]:
print('For prediction enter features')
F = []
for name in feature_names:
  f = float(input(name))
  F.append(f)
prediction = lr.predict(scaler.transform(np.asarray(F).reshape(1,-1)))
print('Features: ', F, ' Predict - ', target_names[prediction])

For prediction enter features
sepal length (cm)6
sepal width (cm)3
petal length (cm)5
petal width (cm)2
Features:  [6.0, 3.0, 5.0, 2.0]  Predict -  ['virginica']
