In [21]:
import numpy as np
from sklearn import datasets

# Load Data

In [22]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [23]:
X = iris['data']
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
labels = np.unique(y)
labels

array([0, 1, 2])

# Split

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)
print(np.bincount(y))
print(np.bincount(y_train))
print(np.bincount(y_test))

[50 50 50]
[35 35 35]
[15 15 15]


# Normalize

In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)            #  get mean and std from X_train, which used fo both - X_train and X-test
X_train_std = scaler.transform(X_train)
X_test_std = scaler.transform(X_test)

# Model

In [26]:
from sklearn.linear_model import Perceptron
bc = Perceptron(eta0=0.1, random_state=1)
bc.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=1, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

# Validation

In [27]:
from sklearn.metrics import accuracy_score
y_pred = bc.predict(X_test_std)
print('accuracy - ', accuracy_score(y_test, y_pred))

accuracy -  0.9555555555555556


# Predict

In [29]:
prediction = bc.predict([[6, 3, 5, 2]])
print(target_names[prediction])

['virginica']
