In [1]:
import numpy as np
from sklearn import datasets

# Load Data

In [2]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [3]:
X = iris['data']
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
labels = np.unique(y)
labels

array([0, 1, 2])

# Split

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)
print(np.bincount(y))
print(np.bincount(y_train))
print(np.bincount(y_test))

[50 50 50]
[35 35 35]
[15 15 15]


# Model

In [5]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(criterion='gini', n_estimators=25, n_jobs=2)
#
#  Supported criteria are “gini” for the Gini impurity and “entropy” for the information gain.
#  n_estimators - trees number(iterations),  n_jobs - parallel execution of kernels in processor
#
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=2,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

# Validation

In [7]:
from sklearn.metrics import accuracy_score
y_pred = rf.predict(X_test)
print('accuracy - ', accuracy_score(y_test, y_pred))

accuracy -  0.9777777777777777


# Predict

In [8]:
prediction = rf.predict([[6, 3, 5, 2]])
print(target_names[prediction])


['virginica']


In [9]:
print('For prediction enter features')
F = []
for name in feature_names:
  f = float(input(name))
  F.append(f)
prediction = rf.predict(np.asarray(F).reshape(1,-1))
print('Features: ', F, ' Predict - ', target_names[prediction])

For prediction enter features
sepal length (cm)6
sepal width (cm)3
petal length (cm)2
petal width (cm)1
Features:  [6.0, 3.0, 2.0, 1.0]  Predict -  ['versicolor']
