In [1]:
import numpy as np
from sklearn import datasets

# Load Data

In [2]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [3]:
X = iris['data']
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
labels = np.unique(y)
labels

array([0, 1, 2])

# Split

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)
print(np.bincount(y))
print(np.bincount(y_train))
print(np.bincount(y_test))

[50 50 50]
[35 35 35]
[15 15 15]


# Normalize

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)            #  get mean and std from X_train, which used fo both - X_train and X-test
X_train_std = scaler.transform(X_train)
X_test_std = scaler.transform(X_test)

# Model

In [6]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', C=1.0, random_state=1)
svm.fit(X_train_std, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

# Validation

In [14]:
from sklearn.metrics import accuracy_score
y_pred = svm.predict(X_test_std)
print('accuracy - ', accuracy_score(y_test, y_pred))

accuracy -  0.9777777777777777


# Predict

In [8]:
prediction = svm.predict([[7.7, 3.8, 6.7, 2.2]])
print(target_names[prediction])


['virginica']


In [15]:
print('For prediction enter features')
F = []
for name in feature_names:
  f = float(input(name))
  F.append(f)
prediction = svm.predict(scaler.transform(np.asarray(F).reshape(1,-1)))
print('Features: ', F, ' Predict - ', target_names[prediction])

For prediction enter features
sepal length (cm)4
sepal width (cm)3
petal length (cm)1
petal width (cm)0.2
Features:  [4.0, 3.0, 1.0, 0.2]  Predict -  ['setosa']
